### ISSUE TITLE
using custom styles for sidebars

### ISSUE THREAD

**Issue by tablatronix** [webketje/GS-Custom-Settings#13]
It should just use native css selectors so it is compatible with admin theming.

class="current" for example, not adding its own orange css rules.

**Comment by tablatronix** [comment]
I see why there is a problem here you are using inputs for renaming.
Maybe add the tab inputs dynamically on double click of the links or something

using Click-to-edit
http://knockoutjs.com/documentation/hasfocus-binding.html

**Comment by webketje** [comment]
True, I'll sort it out for v0.6. I already noticed there were some incompatibilities when I tried out the Flat Blue admin theme. It's quite simple, I just need to move the `current` class to the anchor. Last resort I'll try the `hasFocus` binding.

**Comment by webketje** [comment]
Also would like to update the background-color/border of selected items & icons in Edit mode. Is there any class that applies only these? Or should I check manually whether an admin.xml file exists in theme folder?

**Comment by tablatronix** [comment]
not until 3.4 ( see bottom of style.php in master ) There will also be labels and fontawesome in core.

**Comment by webketje** [comment]
Solved in the coming version, 0.6
