### ISSUE TITLE
Add Date field (native HTML5) / jQuery fallback

### ISSUE THREAD

**Issue by webketje** [webketje/GS-Custom-Settings#9]

**Comment by tablatronix** [comment]
I wouldn't even add a fallback, let users do that or ancillary plugins, just use html5 so they can be identified for plugability.

```
// jqueryui datepicker
$('input[type=date]').datepicker();
```

**Comment by webketje** [comment]
jQuery UI is included by default with GS, am I right?

**Comment by tablatronix** [comment]
Yes

**Comment by webketje** [comment]
Included in 0.6
